# Site settings
title: SUGERPLAY
email: yoojin@sugernspice.com
description: > # this means to ignore newlines until "baseurl:"
  Suger playing spicily.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sugerplay.github.io" # the base hostname & protocol for your site
twitter_username: sugerplay
github_username:  sugerplay

# Build settings
# markdown: kramdown

markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]